# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Qin Wu'
description: '21 MISM @Washington University in St. Louis'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
resume: 'resume'
linkedin: 'qin-wu-67517a192/'
instagram: 'oneariaaa'
github-user: 'oneariaaa'
weixin:'weixin_barcode.jpg'
email: 'wuqin_1997@163.com'

social-links-order: [resume, github-user, linkedin, instagram, weixin, email]

# Advanced settings
plugins:
  - jekyll-remote-theme

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: resume
    url-pattern: oneariaaa.github.io/__USERNAME__
    icon-class: far fa-2x fa-address-card

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: weibo
    url-pattern: weibo.com/__USERNAME__

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: weixin
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-weixin

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open
